### ISSUE TITLE
Plotting prior distribution from pyro model 

### ISSUE THREAD

**Issue by andersdot** [arviz-devs/arviz#1128]
I want to plot the kde of my prior in a matrix plot but I'm not sure how to extract prior information from my pyro model. You give examples for the posterior predictive and prior predictive in the Inference Data Cookbook (shown below), is there a similar function for the prior? The `PyroConverter` class suggests there is but I can't figure it out. Cheers 

```python
nuts_kernel = NUTS(model, jit_compile=True, ignore_jit_warnings=True)
mcmc = MCMC(nuts_kernel, num_samples=draws, warmup_steps=draws,
            num_chains=chains, disable_progbar=True)
mcmc.run(**eight_school_data)
posterior_samples = mcmc.get_samples()
posterior_predictive = Predictive(model, posterior_samples).get_samples(
    eight_school_data['J'], eight_school_data['sigma']
)
prior = Predictive(model, num_samples=500).get_samples(
    eight_school_data['J'], eight_school_data['sigma']
)
```

**Comment by OriolAbril** [comment]
The example in the [cookbook](https://arviz-devs.github.io/arviz/notebooks/InferenceDataCookbook.html#From-pyro) is a somewhat complete overview of the `from_pyro` capabilities, some more details can be found in the [API reference](https://arviz-devs.github.io/arviz/generated/arviz.from_pyro.html#arviz.from_pyro). We know the documentation on converter functions can be improved and we are [working on it](https://github.com/arviz-devs/arviz/wiki/Season-of-Docs-2020-ideas#conversion-guides).

For the time being, this issue can be an extension to docs. The argument to add prior data using `from_prior` is `prior`, which is the result of `Predictive` like the `prior` variable in the code above. There is a trick though because `prior` contains both prior and prior predictive variables. 

    idata = az.from_pyro(prior=prior)

will populate the `prior` group with prior and prior predictive variables. 

    idata = az.from_pyro(mcmc, prior=prior)

will populate both `prior` and `prior_predictive` groups. In any of the two cases coords and dims arguments can also be used to name dimensions and use custom coordinate values. 

Once you already have an `InferenceData` object, you can check the data in the `prior` group doing `idata.prior` and plot them using the `group="prior"` argument in most of the plotting functions. For example:

    plot_posterior(idata, group="prior")

**Comment by ahartikainen** [comment]
Also, if plot is still missing group argument you can manually plot the group

    az.plot_trace(idata.prior)
