### ISSUE TITLE
az.plot_dist(kind=hist) and bins arg raises exception

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1306]
Following code raises an exception

```
import arviz as az
newcomb = pd.read_csv("https://raw.githubusercontent.com/avehtari/ROS-Examples/master/Newcomb/data/newcomb.txt")
az.plot_dist(newcomb.values, hist_kwargs=dict(bins=30))
```

![image](https://user-images.githubusercontent.com/7213793/87886258-5edace80-c9d0-11ea-862f-33f601792400.png)

Matplotlib version does not
```
import matplotlib.pyplot as plt
newcomb = pd.read_csv("https://raw.githubusercontent.com/avehtari/ROS-Examples/master/Newcomb/data/newcomb.txt")
plt.hist(newcomb.values,bins=30)
```
![image](https://user-images.githubusercontent.com/7213793/87886279-83cf4180-c9d0-11ea-82f0-a4955b9cab34.png)

**Comment by ahartikainen** [comment]
Yes, there is an error. We probably should grab the bins returned from the plot call.

https://github.com/arviz-devs/arviz/blob/d046cea6d2847c63f9207826d8e478e429ae2374/arviz/plots/backends/matplotlib/distplot.py#L126

from 

`n, _, _ = ax.hist(np.asarray(values).flatten(), bins=bins, **hist_kwargs)`

to

`n, bins, _ = ax.hist(np.asarray(values).flatten(), bins=bins, **hist_kwargs)`

**Comment by Samasth** [comment]
Hi @canyon289 I am a beginner to open source can I please work on this?

**Comment by canyon289** [comment]
@Samasth of course!

A couple of pointers.

1. The contributing guide has a lot of information on how to get started
2. Testing is important with ArviZ so expect to fix the issue in code, but also add tests to our test suite to ensure no one breaks the shiny new functionality moving forward.
3. Feel free to ask questions!

**Comment by Samasth** [comment]
@canyon289 can you please elaborate a bit on the second step. I see the test suite which has tests in base_tests and external_tests. How would you want me to test this part, as we need to plot a graph and make sure that no exception is thrown.
Thanks.

**Comment by OriolAbril** [comment]
The idea would be something like [this test](https://github.com/arviz-devs/arviz/blob/master/arviz/tests/base_tests/test_plots_bokeh.py#L214) where instead of using `continuous_model["y"]` as data a list was passed as data. Similar [test](https://github.com/arviz-devs/arviz/blob/master/arviz/tests/base_tests/test_plots_matplotlib.py#L392) with matplotlib here too in case it helps.

We want to make sure the preprocessing works and the figure is generated, what is not checked is the generated figure so things like color, axis limits... are generally not chekced. In this particular case we actually want to check the preprocessing basically so everything should work fine.
