### ISSUE TITLE
Forest plot order by coords and not variables.

### ISSUE THREAD

**Issue by sperezconesa** [arviz-devs/arviz#1381]
## Short Description

Hello everyone!
In my model I have to variables that I want to compare each of them has several coords. I would like to plot them with a forest plot. With this code:
```python
pm.forestplot(my_model, varnames=['mu_o_c','mu_fo_c'], rope=(0,0), combined=True)
```
 I get this:
![image](https://user-images.githubusercontent.com/27727343/93207743-b6d94b80-f75b-11ea-8cd7-25ba792b2a3d.png)
But actually I would like them to be ordered as mu_o_c 0, mu_fo_c 0, mu_o_c 1, mu_fo_c 1 ... and with different colors since mu_fo_c and mu_o_c are the two states I am trying to compare. 

I have used pymc3 to generate the data. Let me know if there is anything I can tell you extra.
Thank you very much for your time!
Best,
Sergio

**Comment by OriolAbril** [comment]
It is not possible to mix the order between variables and coordinates. In most cases, different variables have completely different dimensions and it would not make much sense either. In cases such as this, where a different ordering does make sense, it is possible to combine the two variables into a single one and once both 0-36 and o-fo are both coordinates, modify the ordering.

Assuming the 0-36 dimension has the same name for both variables and it's called `mu_dim`, the code to combine them should look like this:

```
ds = my_model.posterior  # alias to shorten the code, my_model must be InferenceData
ds["mu"] = xr.concat((ds["mu_o"], ds["mu_fo"]), dim="mu_kind").assign_coords(mu_kind=["o", "fo"])
# if desired, delete the original two variables and leave mu only, I have not
```

Afterwards, we can choose the order with the `transpose` method. Right after the `concat` due to xarray conventions, the plot will be:

```
az.plot_forest(ds, var_names="mu", combined=True)
```

![image](https://user-images.githubusercontent.com/23738400/93252354-a47c0380-f795-11ea-8482-9fb6ffbc7df6.png)

which can be transposed to modify the desired order:

```
az.plot_forest(ds.transpose("chain", "draw", "mu_dim", "mu_kind"), var_names="mu", combined=True)
```

![image](https://user-images.githubusercontent.com/23738400/93252741-2d933a80-f796-11ea-99cc-965969453517.png)

As far as I know, color in purely model dependent in `plot_forest` so it can't be modified for variables nor coords within the same model. To get different colors we have to pass the two variables as different models:

```
az.plot_forest(
    (ds["mu_o"].rename("mu"), ds["mu_fo"].rename("mu")), 
    combined=True, 
    colors=["k", "C2"], 
    model_names=["o", "fo"]
)
# or alternatively
az.plot_forest(
    (ds.sel(mu_kind="o"), ds.sel(mu_kind="fo")),
    var_names="mu",
    combined=True, 
    colors=["k", "C2"], 
    model_names=["o", "fo"]
)
```

![image](https://user-images.githubusercontent.com/23738400/93253579-5bc54a00-f797-11ea-9b53-e7562b4ad404.png)

**Comment by sperezconesa** [comment]
Great!  It worked! now I have another small problem, the labels overlap a bit:
![image](https://user-images.githubusercontent.com/27727343/93485008-dfe81080-f902-11ea-911c-25af77f30c3f.png)

**Comment by OriolAbril** [comment]
I think for this you'll either have to make the figure size taller or reduce the text size.

**Comment by sperezconesa** [comment]
Increasing the figsize doesn't seem to work. Reducing the text size does aliviate. Is there a way to increase the padding maybe through matplotlib commands?

**Comment by OriolAbril** [comment]
Not sure, maybe `plt.tight_layout`?

**Comment by sperezconesa** [comment]
It seems like tight_layout+figsize+textsize seems to do the trick!
Muchas gracias! 🙏
