### ISSUE TITLE
Add dataframe to InfData examples to cookbook

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#1490]
## Tell us about it
Add dataframe to InfData examples to cookbook

https://arviz-devs.github.io/arviz/getting_started/InferenceDataCookbook.html?highlight=cookbook

```
import pandas as pd
import xarray as xr
import arviz as az
import numpy as np

df = Datasets.Waterbury.to_dataframe()
df["chain"] = 1
df["draw"] = np.arange(len(df), dtype=int)
df = df.set_index(["chain", "draw"])
xdata = xr.Dataset.from_dataframe(df)
idata = az.InferenceData(posterior=xdata)
```

**Comment by ColCarroll** [comment]
Note that this is reasonably also a recipe for csv -> InferenceData, which is reasonably a recipe for a (tidy) dataframe in R to turn into InferenceData.

By "tidy" I specifically mean, it would have a "draw" and "chain" column, and each row would correspond to a single draw from a single chain of an mcmc run.

**Comment by shivam5522** [comment]
I would like to contribute to this. Can someone exactly guide me what should I do in this?

**Comment by OriolAbril** [comment]
Hi @shivam5522, welcome! 

The [cookbook page](https://arviz-devs.github.io/arviz/getting_started/InferenceDataCookbook.html) in the docs is generated from a jupyter notebook that you can find at https://github.com/arviz-devs/arviz/blob/master/doc/source/getting_started/InferenceDataCookbook.ipynb. The idea of this issue is to follow the pattern of `np.ndarray` and `dict` and add a couple cells to the notebook (between the dict and pymc3 examples) and add a variation of the code above to show how to generate an InferenceData from a pandas dataframe.

**Comment by antreev-brar** [comment]
I would like to contribute to this.

**Comment by OriolAbril** [comment]
Hi @antreev-brar as per our [contributing guide](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#if-the-issue-ticket-has-someone-assigned-to-it) it has been two weeks since the issue was assigned and there has been no further activity we can assign it anew to you. However, given it has been exactly two weeks, if you don't mind let's wait until tomorrow before you start to give @shivam5522 time to submit a PR if he has already started working on it. 

I also want to use the opportunity to remember to open PRs early using WIP if it is still a work in progress, it is never too early :). Also, @shivam5522 there are other very similar issues available, for example https://github.com/arviz-devs/arviz/issues/1486, each point of the checklist can be tackled independently, and some also have issues like this already containing the code snippets. Let me know if any of you needs any help, either here on on https://gitter.im/arviz-devs/community, there we can chat one on one too if you prefer it.

**Comment by Rishabh261998** [comment]
I would like to contribute to this issue if it's still isn't resolved. Thank You

**Comment by OriolAbril** [comment]
Hi @Rishabh261998 , thanks for your interest in contributing to ArviZ :) 

This may feel like a _deja vu_ but I will repeat the same I said two weeks ago, now with the roles reversed:

> as per our contributing guide it has been two weeks since the issue was assigned and there has been no further activity we can assign it anew to you. However, given it has been exactly two weeks, if you don't mind let's wait until tomorrow before you start to give @antreev-brar  time to submit a PR if he has already started working on it.
>
> I also want to use the opportunity to remember to open PRs early using WIP if it is still a work in progress, it is never too early :). 
> Also, again, @shivam5522 and @antreev-brar  there are other very similar issues available, for example #1486, each point of the checklist can be tackled independently, and some also have issues like this already containing the code snippets. Let me know if any of you needs any help, either here on on https://gitter.im/arviz-devs/community, there we can chat one on one too if you prefer it.

**Comment by Rishabh261998** [comment]
@OriolAbril as you have mentioned above that we need to add some code in this python notebook( https://github.com/arviz-devs/arviz/blob/master/doc/source/getting_started/InferenceDataCookbook.ipynb ), but I'm unable to access it.

**Comment by OriolAbril** [comment]
True, we renamed it recently: https://github.com/arviz-devs/arviz/blob/main/doc/source/getting_started/CreatingInferenceData.ipynb
