### ISSUE TITLE
`az.from_numpyro` crashes when running MCMC with `thinning != 1`

### ISSUE THREAD

**Issue by kpj** [arviz-devs/arviz#1618]
**Describe the bug**
When using `az.from_numpyro` to import an MCMC run from `numpyro`, a `ValueError` is thrown if the MCMC was run with, e.g., `thinning=2`.

**To Reproduce**
Running
```python
import arviz as az
import numpy as np
import numpyro
import numpyro.distributions as dist
from jax import random
from numpyro.infer import MCMC, NUTS


data = np.random.normal(10, 3, size=100)

def model(data):
    numpyro.sample(
        'x',
        dist.Normal(
            numpyro.sample('loc', dist.Uniform(0, 20)),
            numpyro.sample('scale', dist.Uniform(0, 20)),
        ),
        obs=data,
    )


kernel = NUTS(model)
mcmc = MCMC(NUTS(model), 100, 200, thinning=2)

mcmc.run(random.PRNGKey(0), data=data)
mcmc.print_summary()

az.from_numpyro(mcmc)  # crash
```
will crash with
```python
ValueError: cannot reshape array of size 10000 into shape (1,200,100)
```

Setting `thinning=1` will prevent the crash.

**Expected behavior**
I would expect `az.from_numpyro(mcmc)` to not crash.

**Additional context**
I am using arviz `0.11.2` and numpyro `0.6.0`.

**Comment by OriolAbril** [comment]
Thanks for reporting, it looks like the culprit is this line:

https://github.com/arviz-devs/arviz/blob/59575274a5921acae24930733b7125c96ff8e97b/arviz/data/io_numpyro.py#L94

which gathers info from the numpyro object in order to be able to reshape the samples accordingly afterwards (which is where the error is triggered). Taking thinning into account when defining `self.ndraws` should fix the issue. It looks like `thinning` is stored in the same way as `num_chains` and `num_draws`: https://github.com/arviz-devs/arviz/blob/59575274a5921acae24930733b7125c96ff8e97b/arviz/data/io_numpyro.py#L94

Do you want to submit a PR for this?

**Comment by kpj** [comment]
Thanks for the information! I'd be happy to submit a PR.

Would the fix be as easy as dividing `self.ndraws` by `posterior.thinning` in the line after https://github.com/arviz-devs/arviz/blob/59575274a5921acae24930733b7125c96ff8e97b/arviz/data/io_numpyro.py#L94?

**Comment by OriolAbril** [comment]
> Would the fix be as easy as dividing self.ndraws by posterior.thinning in the line after 

I think so

**Comment by kpj** [comment]
It seems to work for me, I submitted a [PR](https://github.com/arviz-devs/arviz/pull/1619).
