### ISSUE TITLE
Error with plot_joint: number of rows must be a positive integer, not 0

### ISSUE THREAD

**Issue by PHJT003** [arviz-devs/arviz#1633]
**Describe the bug**
The `az.plot_joint()` function does not display any plot.

**To Reproduce**
I uploaded a Jupyter Notebook with the error [here](https://github.com/PHJT003/sos/blob/dc7baff3d2d186921d90d46d7f264b280996139e/arviz/az.plot_joint.ipynb).

Alternatively, the error can be reproduced using one of the examples on the [ArviZ site](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_joint.html) that use `kind='kde'` (e.g., 3rd plot). 

**Expected behaviour**
I would like to plot the figure displayed in [Osvaldo Martin's Jupyter Notebook](https://github.com/aloctavodia/BAP/blob/master/code/Chp2/02%20Programming%20probabilistically.ipynb) (**cell 16**).

**Additional context**
I am running my code on Python 3.6.13, inside an Anaconda environment. My OS is Windows 10.

Below is some information about the modules I am using.

```
# Name                    Version                   Build  Channel
arviz                     0.3.1                    pypi_0    pypi
matplotlib                3.3.4            py36haa95532_0
matplotlib-base           3.3.4            py36h49ac443_0
pymc3                     3.6                      py36_0
```

Thank you very much for your help.

Best wishes,
Valerio

**Comment by OriolAbril** [comment]
Hi, thanks for reporting, arviz 0.3.1 is very old, and a lot has changed since then. I am afraid I can't help with that and no fixes will be added to this version. From this line: 

```
C:\ProgramData\Anaconda3\envs\bap\lib\site-packages\arviz\plots\jointplot.py in plot_joint(data, var_names, coords, figsize, textsize, kind, gridsize, contour, fill_last, joint_kwargs, marginal_kwargs)
     84 
     85     # Instantiate figure and grid
---> 86     fig, _ = plt.subplots(0, 0, figsize=figsize, constrained_layout=True)
     87     grid = plt.GridSpec(4, 4, hspace=0.1, wspace=0.1)
     88
```

it looks like the error is this `0, 0` hardcoded in arviz, which used to work and was probably deprecated by matplotlib at some point. As I was saying, arviz 0.3.1 is old, yet you are using the latest matplotlib which is not compatible anymore.

You can either downgrade matplotlib (I don't know to which version, you can look at the release dates on pypi for both packages and get the matplotlib released around arviz 0.3.1) or upgrade python, arviz and pymc3. I recommend upgrading, unless you have a frozen environment with old versions where you are sure things will run, which does not seem to be the case. However, upgrading could make you update some of the code in your notebook, but if you plan to use arviz and pymc3 somewhere else, not only to reproduce the book, you are better off using the latest versions.

As general info, `plot_joint` is deprecated because `plot_pair` allows to generate the same plots `plot_joint` does and may more, so it did not make sense to keep it around and maintain duplicated code. You can see an example of plot pair replacing plot joint here: https://arviz-devs.github.io/arviz/examples/plot_joint.html

**Comment by PHJT003** [comment]
> As general info, `plot_joint` is deprecated because `plot_pair` allows to generate the same plots `plot_joint` does and may more, so it did not make sense to keep it around and maintain duplicated code. You can see an example of plot pair replacing plot joint here: https://arviz-devs.github.io/arviz/examples/plot_joint.html

Hi @OriolAbril !
Thanks for your help.

I used `az.plot_pair()` and it worked.!

However, I still could not include the marginal distributions in the figure. When I use the argument `marginals = True`, I get:

```
TypeError: plot_pair() got an unexpected keyword argument 'marginals'
```

I reproduced this error in the same Jupyter Notebook I linked in my first post.

Best wishes,
Valerio

**Comment by ahartikainen** [comment]
Hi, did you update your arviz?

In notebook

    !python -m pip install arviz -U

(And remember to restart notebook)

**Comment by PHJT003** [comment]
Hi @ahartikainen
I decided to start from scratch with a fresh Anaconda environment: I installed all the dependencies, including the latest version of ArviZ.

Now, everything works fine, thank you a lot!
Also, thanks for developing and maintaining such an amazing library!

Best wishes,
Valerio
