### ISSUE TITLE
plot_dist_comparison has no warning when max_subplots goes over the max

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#1680]

**Comment by alexisperakis** [comment]
Hi, first-time contributor here, can I be assigned to this issue? Is there any further info?
Thanks

**Comment by ColCarroll** [comment]
Welcome! Happy to assign to you.

You can check out [here](https://github.com/arviz-devs/arviz/blob/main/arviz/plots/traceplot.py#L200-L212) in traceplot, there are 12 lines that get the "plotters", and check that against the maximum number of subplots. I think this would be fixed by:

1. Putting some very similar code [here](https://github.com/arviz-devs/arviz/blob/main/arviz/plots/distcomparisonplot.py#L132)
2. Do something similar to [this test](https://github.com/arviz-devs/arviz/blob/main/arviz/tests/base_tests/test_plots_matplotlib.py#L231), but with `plot_dist_comparison`: you'll want to ask for a plot that would generate more than 6 subplots, and verify you still only get 6.

Let me know if you need more pointers!

**Comment by alexisperakis** [comment]
Hi, I would like to ask you a question.
We want to check if `dc_plotters` goes over the limit.
If I understood correctly, is the maximum number of plots that arviz allows to be displayed the variable `len_plots`? If this is the case, I need to compare it with this variable

**Comment by OriolAbril** [comment]
The behaviour is already correct, we want to cut `dc_plotters` to have at most `len_plots`. The issue is that when `dc_plotters` is actually truncated, a warning must be shown, like it's done in the code example linked above by Colin. If `dc_plotters` is short enough that it doesn't need to be truncated, then there should be no warning.

**Comment by alexisperakis** [comment]
> The behaviour is already correct, we want to cut `dc_plotters` to have at most `len_plots`. The issue is that when `dc_plotters` is actually truncated, a warning must be shown, like it's done in the code example linked above by Colin. If `dc_plotters` is short enough that it doesn't need to be truncated, then there should be no warning.

Thank you
