### ISSUE TITLE
Update PyMC3 version string parsing

### ISSUE THREAD

**Issue by brandonwillard** [arviz-devs/arviz#1708]
We're seeing [an issue](https://github.com/pymc-devs/pymc3/pull/4726/checks?check_run_id=2683532131#step:7:305) with version strings of the form `"4.0.0.dev0"` in `_monkey_patch_pymc3`.:
```python
/usr/share/miniconda/envs/pymc3-dev-py37/lib/python3.7/site-packages/arviz/data/io_pymc3.py:46: in _monkey_patch_pymc3
    if tuple([int(x) for x in pm.__version__.split(".")]) < (3, 9):  # type: ignore
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7f4f23a2a990>

>   if tuple([int(x) for x in pm.__version__.split(".")]) < (3, 9):  # type: ignore
E   ValueError: invalid literal for int() with base 10: 'dev0'
```

**Comment by ahartikainen** [comment]
from packaging import version
    packaging.version.parse(pm.__version__) < packaging.version.parse("3.9")

**Comment by OriolAbril** [comment]
We should probably finish and merge #1660 instead of working on `io_pymc3.py`. pymc3 4.x already has the converter in the pymc codebase which does not need monkeypatching anymore and should not have this issue to begin with. The converter we still have at ArviZ should only be kept here for backwards compatibility and be imported at runtime only if pymc3 < 4.0 is installed.
