### ISSUE TITLE
How can I suppress the warning of `plot_hdi` ?

### ISSUE THREAD

**Issue by integzz** [arviz-devs/arviz#1758]
## Short Description

When I use `plot_hdi`, there pop up the following warning:

/usr/local/Caskroom/miniconda/base/envs/kaggle/lib/python3.9/site-packages/arviz/stats/stats.py:456: FutureWarning: hdi currently interprets 2d data as (draw, shape) but this will change in a future release to (chain, draw) for coherence with other functions

How can I deal with it besides using the `warnings` module ?

## Code Example or link

```python
_, ax = plt.subplots(dpi=100)

ax.plot(x, y, 'b.')
ax.plot(x, α_m + β_m * x, c='k',
         label=f'y = {α_m:.2f} + {β_m:.2f} * x')

az.plot_hdi(x, ppc['y_pred'], hdi_prob=0.5, color='gray', ax=ax)
az.plot_hdi(x, ppc['y_pred'], color='gray', ax=ax)

ax.set(xlabel='x', ylabel='y')
```

ArviZ version: 0.11.2

**Comment by OriolAbril** [comment]
I would recommend using xarray objects or 3d data that follows the `chain, draw, *shape` convention. `hdi` and by extension `plot_hdi` are the only functions in the library that don't follow this convention when taking array inputs which is why you are seeing this warning. In a future release this will be changed to ensure coherence throughout the library. 

I strongly recommend adding your posterior predictive samples to the `InferenceData` object where you have your posterior samples. The `ppc['y_pred']` makes me think you are using pymc3, so you can follow the pattern in https://nbviewer.jupyter.org/github/pymc-devs/pymc-examples/blob/main/examples/case_studies/rugby_analytics.ipynb for example to add the posterior predictive the the InferenceData. This will label the dimensions of your data so there is no doubt about what are chain and draw dimensions and what are batch dimensions.

The 2nd option would be to use 3d data so that instead of having `sample, extra_dim` (with sample being the chain and draw dims stacked together) you have `chain, draw, extra_dim`. You can do that directly from [`sample_posterior_predictive` in pymc3](https://docs.pymc.io/api/inference.html#pymc3.sampling.sample_posterior_predictive) using the `keep_size` argument.

**Comment by integzz** [comment]
Thank you for your suggestion, it is helpful. Closing.
