### ISSUE TITLE
pair_plot 1D style seems not affected

### ISSUE THREAD

**Issue by jecampagne** [arviz-devs/arviz#1950]
Hi, 
I do not manage to change the style of the diagonal Kde of pair_plot may be I am wrong but cannot find an example: my wish is to get 1D pdf ploted in red color. Thanks   

```python
ax = az.plot_pair(
    spl_true,
    kind="kde",
    var_names=labels,
    kde_kwargs={
        "hdi_probs": [0.3, 0.6, 0.9],  # Plot 30%, 60% and 90% HDI contours
        "contourf_kwargs": {"cmap": "Reds"},
        "plot_kwargs":{"c":"red"}
    },
    marginals=True, textsize=20,
);
```

![image](https://user-images.githubusercontent.com/20539759/145712896-c9506a95-ca03-4c3f-9bd9-08699bb6191a.png)

Arviz Version : '0.11.4'

**Comment by ahartikainen** [comment]
Can you try with 

`"plot_kwargs":{"color":"red"}`

?

What you have should work, I don't see anything wrong with it.

**Comment by OriolAbril** [comment]
You need to use `marginal_kwargs` instead of `plot_kwargs`. In your case I believe it should be `marginal_kwargs={"color": "red"}`. As indicated in https://arviz-devs.github.io/arviz/api/generated/arviz.plot_pair.html, marginal_kwargs are passed to plot_dist, so you have to make sure the keys are valid arguments for plot_dist.

We do have to check what happens with plot_kwargs though as it is an argument but is not documented in the docstring :confused:

**Comment by jecampagne** [comment]
Thanks
At least  I had tried unsuccessfully `plot_kwargs":{"color":"red"}`.

**Comment by agustinaarroyuelo** [comment]
Closing this as `marginal_kwargs={"color": "red"}` works. I opened #2073 to handle missing documentation for `plot_kwargs`.
