### ISSUE TITLE
Axis limit in function plot_pair

### ISSUE THREAD

**Issue by MCruzReyes** [arviz-devs/arviz#1999]
I am trying to select the axis limit of every subplot using the function "plot_pair". 

Here is the example:

```
import arviz as az
centered = az.load_arviz_data('centered_eight')
coords = {'school': ['Choate', 'Deerfield']}
az.plot_pair(centered,
            var_names=['theta', 'mu'],
            coords=coords,
            textsize=18,
            kind='hexbin')

```

![a](https://user-images.githubusercontent.com/79953450/159127135-230be3b1-a54f-4ab1-a530-68dc4518b452.png)

How can I change the x-axis of the first subplot from [-10,30] to [-20,20]? Is it possible to change the axis of each subplot separately?

**Comment by OriolAbril** [comment]
**Note: I will be speaking about [ArviZ development version](https://arviz-devs.github.io/arviz/getting_started/Installation.html#development), not about the behaviour in previous releases**

ArviZ returns the matplotlib axes used to generate the plot in a numpy array. Each position in the numpy array corresponds to
the axes in that position in the plot. In plot_pair, the x axis are shared in each column, and the y axis is shared in each row (excluding marginals if present), so modifying the x axis in the lower row updates the x axis in all plots:

```
import arviz as az
centered = az.load_arviz_data('centered_eight')
coords = {'school': ['Choate', 'Deerfield']}
ax = az.plot_pair(centered,
            var_names=['theta', 'mu'],
            coords=coords,
            textsize=18,
            kind='hexbin')
ax[1,0].set_xlim([-10,30])
ax[1,1].set_xlim([-20,20])
```

generates

![imatge](https://user-images.githubusercontent.com/23738400/159163568-703882a2-65f0-4f3b-889c-a24c38f41f75.png)

To be able to change the axis independently for each subplot you will need to generate your array of matplotlib axes manually,
then manually set the limits for each subplot. If you do that however you'll probably want to activate the ticklabels in all plots,
otherwise readers will have no way of knowing what are the x values in the upper left subplot in your example (and that will get worse in higher dimensions).
