### ISSUE TITLE
Plot visualizing quantiles in time series

### ISSUE THREAD

**Issue by ariddell** [arviz-devs/arviz#2]
It would be great to have a nice, generic version of this:

![](https://cloud.githubusercontent.com/assets/1217238/6197735/be036856-b39f-11e4-840b-0278b934bd71.png)

See https://github.com/mwaskom/seaborn/issues/450 for discussion.

The suggested matplotlib recipes are wanting by comparison, I think (http://matplotlib.org/users/recipes.html).

**Comment by twiecki** [comment]
+1

**Comment by ariddell** [comment]
I'd settle for something simpler too, maybe something with a point at the center of a line, like this:

```
p + geom_pointrange(aes(ymin = lower, ymax = upper))
```
from

http://ggplot2.tidyverse.org/reference/geom_linerange.html

Looks like plotnine has this.

**Comment by ahartikainen** [comment]
We could do this with `np.percentile` + for loop with `fill_between`.

**Comment by ariddell** [comment]
That's a good idea.

(I'm not sure this particular plot is high-priority, it's just something I find myself making often with Stan output.)

**Comment by ahartikainen** [comment]
Here is a sketch for `tsplot`. I don't know how much options we should add.

    import numpy as np
    import matplotlib.pyplot as plt
    plt.style.use('ggplot') # this was just used for the examples

    # data
    t = np.linspace(0,100,100)
    y = 5 * np.sin(t/10) + 4*np.random.randn(100*150).reshape(150, 100)
    y_ = 5 * np.sin(t/10) + 4*np.random.randn(100*4000).reshape(4000, 100)

    t__ = np.linspace(0,100,6) 
    y__ = 5 * np.sin(t__/10) + 4*np.random.randn(6*4000).reshape(4000, 6)

    def tsplot(x, y, n=20, percentile_min=1, percentile_max=99, color='r', plot_mean=True, plot_median=False, line_color='k', **kwargs):
        # calculate the lower and upper percentile groups, skipping 50 percentile
        perc1 = np.percentile(y, np.linspace(percentile_min, 50, num=n, endpoint=False), axis=0)
        perc2 = np.percentile(y, np.linspace(50, percentile_max, num=n+1)[1:], axis=0)

        if 'alpha' in kwargs:
            alpha = kwargs.pop('alpha')
        else:
            alpha = 1/n
        # fill lower and upper percentile groups
        for p1, p2 in zip(perc1, perc2):
            plt.fill_between(x, p1, p2, alpha=alpha, color=color, edgecolor=None)


        if plot_mean:
            plt.plot(x, np.mean(y, axis=0), color=line_color)


        if plot_median:
            plt.plot(x, np.median(y, axis=0), color=line_color)
        
        return plt.gca()

Then can be called either in one go:

    tsplot(t, y, n=100, percentile_min=2.5, percentile_max=97.5, plot_median=True, plot_mean=False, color='g', line_color='navy')

![example_n 100](https://user-images.githubusercontent.com/13161958/27450120-4b7c2c9c-5793-11e7-9aaa-b3b751c3a3d0.png)


    tsplot(t, y, n=20, percentile_min=2.5, percentile_max=97.5, plot_median=True, plot_mean=False, color='g', line_color='navy')


![example_n 20](https://user-images.githubusercontent.com/13161958/27450137-567303fa-5793-11e7-9d6f-f5e62970f633.png)


    tsplot(t, y, n=5, percentile_min=2.5, percentile_max=97.5, plot_median=True, plot_mean=False, color='g', line_color='navy')

![example_n 5](https://user-images.githubusercontent.com/13161958/27450149-5b862a7a-5793-11e7-97a6-ff7395656ee1.png)



    tsplot(t, y, n=2, percentile_min=2.5, percentile_max=97.5, plot_median=True, plot_mean=False, color='g', line_color='navy')


![example_n 2](https://user-images.githubusercontent.com/13161958/27450152-5fcbab64-5793-11e7-8fc1-a074ef60aead.png)


    tsplot(t, y_, n=100, percentile_min=2.5, percentile_max=97.5, plot_median=True, plot_mean=False, color='g', line_color='navy')


![example_n 100_sample_large](https://user-images.githubusercontent.com/13161958/27450159-66125f7c-5793-11e7-92d0-d96297d7e0e5.png)


or multiple times

    # IQR
    tsplot(t, y_, n=1, percentile_min=25, percentile_max=75, plot_median=False, plot_mean=False, color='g', line_color='navy', alpha=0.3)
    #  90% interval
    tsplot(t, y_, n=1, percentile_min=5, percentile_max=95, plot_median=True, plot_mean=False, color='g', line_color='navy', alpha=0.3)

![example_n p90_iqr_sample_large](https://user-images.githubusercontent.com/13161958/27450167-6d8173e2-5793-11e7-8b4c-a7c487083a57.png)

    tsplot(t__, y__, n=1, percentile_min=25, percentile_max=75, plot_median=False, plot_mean=False, color='g', line_color='navy', alpha=0.3)
    tsplot(t__, y__, n=1, percentile_min=5, percentile_max=95, plot_median=True, plot_mean=False, color='g', line_color='navy', alpha=0.3)
plt.text(0, -5, "n=2", fontsize=14)

![example_n p90_iqr_sample_large_low_res](https://user-images.githubusercontent.com/13161958/27450398-3d670798-5794-11e7-8eed-0190a8a02e9b.png)

**Comment by ariddell** [comment]
These look great!

I'm inclined to do something very simple like have the posterior mean and single 90% band. This seems to be what is used in Bayesian Data Analysis (e.g., chp 21).

**Comment by ariddell** [comment]
FYI: https://github.com/jasonhilton/ggfan

![readme-example-1](https://user-images.githubusercontent.com/19950/32858313-185fe634-ca19-11e7-8421-02ce3189a071.png)

**Comment by ChampionZP** [comment]
helpful !

**Comment by ColCarroll** [comment]
I'm leaving this closed as out of date, but feel free to reopen if there is interest in taking it up.

Also of interest, it closed because of 
![image](https://user-images.githubusercontent.com/2295568/60633645-aef0ee00-9dd9-11e9-980b-0c99a7b744e7.png)
:joy:

**Comment by steliosm7** [comment]
I would like to ask something, if anyone may help me. I want to use the same code but change in order to use a csv file containing hourly timeseries of a year's (pv production). My goal is to have something like this [https://www.researchgate.net/profile/Hossein-Sangrody/publication/317642809/figure/fig3/AS:727781629501443@1550528070900/hour-profile-of-solar-PV-generation-for-the-case-study.jpg](url)

Thanks in advance, 

You may see a sample of the data below 

1/1/2021   2:00 | 0
1/1/2021 3:00 | 0
1/1/2021 4:00 | 0
1/1/2021 5:00 | 0
1/1/2021 6:00 | 0
1/1/2021 7:00 | 0
1/1/2021 8:00 | 2
1/1/2021 9:00 | 231
1/1/2021   10:00 | 876
1/1/2021   11:00 | 1426
1/1/2021   12:00 | 1704
1/1/2021   13:00 | 1772
1/1/2021   14:00 | 1666
1/1/2021   15:00 | 1401
1/1/2021   16:00 | 903
1/1/2021   17:00 | 259
1/1/2021   18:00 | 4
1/1/2021   19:00 | 0
1/1/2021   20:00 | 0
1/1/2021   21:00 | 0
1/1/2021   22:00 | 0
1/1/2021   23:00 | 0
2/1/2021 0:00 | 0
2/1/2021 1:00 | 0
2/1/2021 2:00 | 0
2/1/2021 3:00 | 0
2/1/2021 4:00 | 0
2/1/2021 5:00 | 0
2/1/2021 6:00 | 0
2/1/2021 7:00 | 0
2/1/2021 8:00 | 1
2/1/2021 9:00 | 190
2/1/2021   10:00 | 673
2/1/2021   11:00 | 1025
2/1/2021   12:00 | 1205
2/1/2021   13:00 | 1174
2/1/2021   14:00 | 1028
2/1/2021   15:00 | 737
2/1/2021   16:00 | 367
2/1/2021   17:00 | 74
2/1/2021   18:00 | 0
2/1/2021 19:00 | 0
2/1/2021   20:00 | 0
2/1/2021   21:00 | 0
2/1/2021   22:00 | 0
2/1/2021   23:00 | 0
3/1/2021 0:00 | 0
3/1/2021 1:00 | 0
3/1/2021 2:00 | 0
3/1/2021 3:00 | 0
3/1/2021 4:00 | 0
3/1/2021 5:00 | 0
3/1/2021 6:00 | 0
3/1/2021 7:00 | 0
3/1/2021 8:00 | 0
3/1/2021 9:00 | 77
3/1/2021   10:00 | 388
3/1/2021   11:00 | 716
3/1/2021   12:00 | 981
3/1/2021   13:00 | 1150
3/1/2021   14:00 | 1047
3/1/2021   15:00 | 854
3/1/2021   16:00 | 489
3/1/2021   17:00 | 123
3/1/2021   18:00 | 1
3/1/2021   19:00 | 0
3/1/2021   20:00 | 0
3/1/2021   21:00 | 0
3/1/2021   22:00 | 0
3/1/2021   23:00 | 0
4/1/2021 0:00 | 0
4/1/2021 1:00 | 0
4/1/2021 2:00 | 0
4/1/2021 3:00 | 0
4/1/2021 4:00 | 0
4/1/2021 5:00 | 0
4/1/2021 6:00 | 0
4/1/2021 7:00 | 0
4/1/2021 8:00 | 0
4/1/2021 9:00 | 38
4/1/2021   10:00 | 152
4/1/2021   11:00 | 239
4/1/2021   12:00 | 278
4/1/2021   13:00 | 244
4/1/2021   14:00 | 172
4/1/2021   15:00 | 152
4/1/2021   16:00 | 187
4/1/2021   17:00 | 107
4/1/2021   18:00 | 4
4/1/2021   19:00 | 0
4/1/2021   20:00 | 0
4/1/2021   21:00 | 0
4/1/2021   22:00 | 0
4/1/2021   23:00 | 0
5/1/2021 0:00 | 0
5/1/2021 1:00 | 0

**Comment by ahartikainen** [comment]
@steliosm7 you will get better answer if asked in a proper forum. That data does not seem to be sampled with mcmc so basically you would first need to create a model + some assumptions to calculate quantiles and it is out of topic for this issue.

**Comment by steliosm7** [comment]
> @steliosm7 you will get better answer if asked in a proper forum. That data does not seem to be sampled with mcmc so basically you would first need to create a model + some assumptions to calculate quantiles and it is out of topic for this issue.

Thank you, @ahartikainen . I will try to figure out the things you asked and I will get back

**Comment by steliosm7** [comment]
@ahartikainen 

I do not want to make an forecast I just want to visualize my data in a similar plot
I have calculated the quantiles for my timeseries, and I have them in a dataframe, can you help me how to change the code above in order to have a similar result ? I have tried to alter it but I do not seem to find solution 

my dataframe or now is like this 

Time | pct0.1 | pct0.2 | pct0.3 | pct0.4 | pct0.5 | pct0.6 | pct0.7 | pct0.8 | pct0.9
01:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
02:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
03:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
04:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
05:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
06:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
07:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
08:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.4 | 1.2
09:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 46.2 | 138.6
10:00 | 246.4 | 340.8 | 445.0 | 559.0 | 673.0 | 737.8 | 802.6 | 843.2 | 859.6
11:00 | 429.8 | 620.6 | 777.8 | 901.4 | 1025.0 | 1153.8 | 1282.6 | 1362.8 | 1394.4
12:00 | 559.2 | 840.4 | 1025.8 | 1115.4 | 1205.0 | 1367.8 | 1530.6 | 1630.4 | 1667.2
13:00 | 606.4 | 968.8 | 1154.8 | 1164.4 | 1174.0 | 1351.2 | 1528.4 | 1648.0 | 1710.0
14:00 | 514.4 | 856.8 | 1031.8 | 1039.4 | 1047.0 | 1232.2 | 1417.4 | 1541.2 | 1603.6
15:00 | 386.0 | 620.0 | 760.4 | 807.2 | 854.0 | 1026.8 | 1199.6 | 1309.0 | 1355.0
16:00 | 259.0 | 331.0 | 391.4 | 440.2 | 489.0 | 621.4 | 753.8 | 836.6 | 869.8
17:00 | 87.2 | 100.4 | 110.2 | 116.6 | 123.0 | 174.2 | 225.4 | 252.6 | 255.8
18:00 | 0.4 | 0.8 | 1.6 | 2.8 | 4.0 | 4.0 | 4.0 | 4.0 | 4.0
19:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
20:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
21:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
22:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
23:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0
00:00 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 | 0.0

**Comment by ahartikainen** [comment]
Again this is not the correct place to ask for help. Please ask this in suitable forum.

**Comment by MarvinLeeSchroeder** [comment]
Thanks to the community for providing great inspiration and helpful code snippets, especially to @ahartikainen and @ariddell. I've combined both to a new python script I'd like to share:

```
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.pyplot as plt

# Define a smooth gradient colormap from blue to red
cmap = LinearSegmentedColormap.from_list("custom_gradient", ['red', 'yellow', 'green', 'blue'])

# Data
t = np.linspace(0, 100, 100)
y = (5 * np.sin(t / 10) + 4 * np.random.randn(100 * 150).reshape(150, 100))

def tsplot(x, y, n=20, percentile_min=1, percentile_max=99, plot_mean=True, plot_median=False, line_color='k', **kwargs):
    # Calculate the lower and upper percentile groups, skipping the 50th percentile
    perc1 = np.percentile(y, np.linspace(percentile_min, 50, num=n, endpoint=False), axis=0)
    perc2 = np.percentile(y, np.linspace(50, percentile_max, num=n + 1)[1:], axis=0)
    perc = np.concatenate((perc1, perc2), axis=0)

    # Generate colors across the colormap based on n
    colors = cmap(np.linspace(0, 1, n))
    
    # Fill lower and upper percentile groups with gradient colors
    for i in range(n):
        plt.fill_between(x, perc[i], perc[-i - 1], color=colors[i], edgecolor=None)
        
    # Plot the mean or median line
    if plot_mean:
        plt.plot(x, np.mean(y, axis=0), color=line_color)
    if plot_median:
        plt.plot(x, np.median(y, axis=0), color=line_color)

    return plt.gca()

# Example call to tsplot
tsplot(t, y, n=24, percentile_min=5, percentile_max=95, plot_median=True, plot_mean=False, line_color='navy')
plt.show()

```

Resulting in this plot:
![output](https://github.com/user-attachments/assets/1e2772f0-0b3a-413f-a06e-8eb432824731)
