### ISSUE TITLE
docs: scrollbar is too small

### ISSUE THREAD

**Issue by grahamgower** [arviz-devs/arviz#2062]
The scrollbar in the docs is far too small, making it very hard to see and very hard to click/drag. There's ample whitespace in the margins for a nice fat scrollbar, so maybe the scrollbar could be left unstyled so the browser can choose how it looks?

**Comment by OriolAbril** [comment]
Hi, thanks for reaching out. We use https://github.com/pydata/pydata-sphinx-theme as our documentation theme. I myself am not even sure if this is theme dependent or even browser dependent. But either way, it isn't something we can fix on ArviZ side only. I'd suggest opening an issue directly there, or letting me know in a comment so I can open it for you and link to this issue as the original source of the problem.

I think the first option is the ideal (and we'll track the changes and make sure we use the new theme version as soon as possible) because I can't answer questions they might have about your configuration in case that were needed to fix the issue.

**Comment by grahamgower** [comment]
Ah, thanks. I see the culprit is https://github.com/pydata/pydata-sphinx-theme/issues/633

**Comment by OriolAbril** [comment]
I have seen the issue tracking this on the pydata-sphinx-theme has been closed, thanks for reporting there too and helping the whole ecosystem improve! 

I'll now close this issue to keep things organized
