### ISSUE TITLE
Update homepage layout and content

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#2098]
We already did some changes in #2087, but we still need to do some more changes to both the layout and content.

Things we should/must do:
* Add a support section
  * logos for sponsors and institutional partners (smallish) and link to https://www.arviz.org/en/latest/sponsors_partners.html
  * Ways to support the project
  * potential references: https://xarray.dev/#sponsors, https://matplotlib.org/ (bottom)
* List the key features of the ArviZ python library more clearly (and if possible in a more appealing way)
  * Potential references: https://xarray.dev/#features, https://numpy.org/, https://matplotlib.org/ (upper right square)

Things to discuss:
* Keep the single column thinner layout or move to a custom wider layout closer to [what we had](https://python.arviz.org/en/v0.12.1/) or to https://matplotlib.org/
* content updates
  * a large chunk of the text should probably go and instead be replaced with some buttons or the like (even if they point to the same place the navbar does). Some ideas: "Install ArviZ", "Example gallery"
* adding some links/cards/showcases? not sure we even have them but it would probably be very nice

cc @sarinac

**Comment by sarinac** [comment]
Hey @OriolAbril - 

Thanks for listing the criteria and providing reference links. They're really helpful! 

I'm not sure how _different_ you imagine the homepage changing, so here is my guess/rough draft. This is all doable with just HTML/CSS changes, but I'll need to figure out how to do it with sphinx (unless I just put everything under the `.. raw:: html`). 

#### What's included in this draft?
* Top section includes Primary CTA (call to action button) "Get Started" which links to [installation guide](https://python.arviz.org/en/latest/getting_started/Installation.html). Top section also includes Secondary CTA "See Gallery" which links to [example gallery](https://python.arviz.org/en/latest/examples/index.html). I think these 2 links are the most important in the landing. For more experienced users, there's a link for "See API Reference".
* Key Features....If you can provide some examples of what you'd like to include then that'll help me figure out the layout/structure/style. I took a guess by sticking the `InferenceData`/`xarray` description in the 4th box. It links to the [documentation explanation on xarray](https://python.arviz.org/en/latest/getting_started/XarrayforArviZ.html#xarray-for-arviz). We can either do 100% descriptions which will link to some part of the documentation, or we can do a hybrid of image/description for each feature. 
* Support: includes cite, sponsors, and donate. I'm not too happy with the layout of these 3 sections, but I had it this way because the "Cite" section naturally just takes up a lot of height. 

#### Other Comments
* The max-width should be set to 1400px (this is usually a standard, and the pydata default css has it), if you want the layout to be wider then we can remove the CSS that is [setting the max-width to 70em](https://github.com/arviz-devs/arviz/blob/main/doc/source/_static/custom.css#L32). In my opinion, I think the current width for ArviZ looks fine. I think matplotlib's width is a little too wide.
* Instead of having a huge ArviZ logo on the top right, I think having 1 example chart would be nice but I'm not sure which one. I could make the example plot's style fit this website's theme more if you give me 1 plot to work with (would probably exist as a standalone image or I can add a new style for ArviZ). 

<img width="463" alt="image" src="https://user-images.githubusercontent.com/20257416/185874869-f6767ed0-29c2-4114-b2c3-6fd99235a74c.png">

**Comment by OriolAbril** [comment]
> Top section includes Primary CTA (call to action button) "Get Started" which links to [installation guide](https://python.arviz.org/en/latest/getting_started/Installation.html).

I would use "install ArviZ" or something a bit more descriptive. We have a getting started navbar section, and installation is one page within that section, not the whole thing so the button "get started" and the navbar section "getting started" would point to different places which I find very unintuitive.

> Key Features....If you can provide some examples of what you'd like to include then that'll help me figure out the layout/structure/style.

I can work on that, it will probably take 1-2 weeks though.

> Support: includes cite, sponsors, and donate. I'm not too happy with the layout of these 3 sections, but I had it this way because the "Cite" section naturally just takes up a lot of height.

The "cite" section doesn't need to contain the whole bibtex style citation, it could be the joss badge, link to extended citation advise and "rendered" citation

> The max-width should be set to 1400px (this is usually a standard, and the pydata default css has it), if you want the layout to be wider then we can remove the CSS that is [setting the max-width to 70em](https://github.com/arviz-devs/arviz/blob/main/doc/source/_static/custom.css#L32). In my opinion, I think the current width for ArviZ looks fine. I think matplotlib's width is a little too wide.

I do not want the content to be wider than the navbar. I think the options to consider are the 100% suggested in the theme docs (which should be equivalent to the 1400px but I am guessing works better with devices of multiple sizes), or something like the 70em (or 65 or 80) to make it wider than the central content column in regular pages but not as wide as the navbar.

> Instead of having a huge ArviZ logo on the top right, I think having 1 example chart would be nice but I'm not sure which one. I could make the example plot's style fit this website's theme more if you give me 1 plot to work with (would probably exist as a standalone image or I can add a new style for ArviZ).

I would actually keep the multiple example images either as a line (before/after or maybe even inside key features?) or as a 3x3 or 3x4 grid in the place of the logo. All the work on the PR was to keep them with roughly that style and hover effect... even if we did some changes to the general layout.

**Comment by sarinac** [comment]
Thanks Oriol! 
* Changed CTA to "Install ArviZ". Good point on the confusion with the Getting Started section, although would it be better if "Getting Started" lands on the Installation guide rather than a table of contents?
* Made the key features part wider (maybe it'll look better?) - just playing around with format in case it could look better. I'm thinking hovering will either a) make the box blue + text white (similar to hovering over plot images), or b) make the text blue.
*  For citation, I reverted back to what was originally there (fits entire page). Still leaning on removing the bibtex citation. Did I cover everything you mentioned?
> The "cite" section doesn't need to contain the whole bibtex style citation, it could be the joss badge, link to extended citation advise and "rendered" citation
* I agree with content width < navbar + 100% width is fine. With this new homepage layout we can go with 100%.
* Good point on the images where the logo was in the first draft...I have no idea why that dropped off my mind. 😅 

Let me know if this homepage covers everything, and if there are sections/layouts/styles you want to change. 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/20257416/186350290-9946f18c-355b-47c6-88de-b027b3cc8459.png">

**Comment by OriolAbril** [comment]
> although would it be better if "Getting Started" lands on the Installation guide rather than a table of contents?

We can try that, it is not very difficult. I can send a PR for this at some point. Everything will work the same and all links will not break if using sphinx cross references (the `` {ref}`target` `` thing).

> Still leaning on removing the bibtex citation

Same for me, I woud only include the rendered citation and the link to https://www.arviz.org/en/latest/support.html#cite (I will add a sphinx target to that header so we can link to it with a sphinx cross reference).

> Let me know if this homepage covers everything, and if there are sections/layouts/styles you want to change.

I think this covers everything. The thing most on the air still is what to put exactly in the key features section. I will post a proposal soonish. Thanks

**Comment by OriolAbril** [comment]
closed by #2119
