### ISSUE TITLE
CmdStanPy reader needs update

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#2276]
Latest changes in the CmdStanPy need handling.

https://github.com/stan-dev/cmdstanpy/issues/693

**Comment by aakhmetz** [comment]
Dear friends,

Sorry for disturbing you, but I wonder if it was updated recently. It was mentioned in #1904 that it was resolved, but I still get the message: AttributeError: 'InferenceMetadata' object has no attribute 'stan_vars_cols'

I have the latest stable versions: cmdstanpy 1.2.0, arviz 1.6.1, stanio 0.3.0 (or 0.4.0)

I am asking because from one side cmdstanpy==1.2.0 allows to use pathfinder, but is broken with this issue, from another side if I use cmdstanpy==1.1.0, then pathfinder is unavail

**Comment by ahartikainen** [comment]
Closed by #2287
