### ISSUE TITLE
`plot_forest` legend order different than `model_names` parameters order

### ISSUE THREAD

**Issue by wd60622** [arviz-devs/arviz#2328]
**Describe the bug**

When passing a list of model_names, the order of the model_names in the legend is reverse of that in the plot. 

For instance, model_names = [A, B, C] would plot each parameter [C, B, A] but with legend of order [A, B, C]

**To Reproduce**
Steps to reproduce the behavior. Ideally a self-contained snippet of code, or link to a notebook or external code. Please include screenshots/images produced with ArviZ here, or the stacktrace including `arviz` code to help.

This can be seen in the second example in the docs: https://python.arviz.org/en/stable/api/generated/arviz.plot_forest.html

**Expected behavior**

Would expect the boxplots to be in the same order as the legend as the same order of the model_names

**Additional context**
Versions of `arviz` and other libraries used, operating system used, and anything else that may be useful.

Initially noticed in 0.17.0

**Comment by OriolAbril** [comment]
If this is critical for you you can try arviz-plots (alpha version of arviz rewrite), where I am adding plot_forest right now and doesn't have this issue.

To install:

    pip install git+https://github.com/arviz-devs/arviz-plots.git@forest

Then:

    import arviz as az # arviz must be imported before
    import arviz_plots as azp
    azp.plot_forest(inference_data)

Note you are installing the forest branch, from which I have an open PR currently, so you have to read the docs in the PR preview for now: https://arviz-plots--34.org.readthedocs.build/en/34/api/generated/arviz_plots.plot_forest.html. The api for multiple models has changed for example, now they should be given as a dict, instead of two data and labels lists.

---

Fixing that in "regular" arviz might not require too many changes, but plot_forest is quite a behemoth, so identifying where the change must go and checking nothing else breaks is bound to take its time. We'd probably accept a PR for this but don't plan on fixing it

**Comment by wd60622** [comment]
Perfect. Thank you for the suggestion!
