### ISSUE TITLE
KDE plot produces strange results

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [arviz-devs/arviz#581]
**Description**
arviz's `plot_kde` produces plot with y-axis that doesn't make sense.

**Reproduce**
https://gist.github.com/absolutelyNoWarranty/f417a052c4b8d05fe3da3b95542f8a0a

**Expected behavior**
The peak of the kde should be around 0.4 for the standard gaussian just like Pandas's kde plot.

**Additional context**
Version of `arviz`: 0.3.2

**Comment by ColCarroll** [comment]
Thanks for the reproducible example - it made it easy to check on this.

It looks like the difference is due to a difference in the algorithm being used - pandas is doing something different at the edge of the data, but arviz stops plotting at the edge.  Rescaling the x-axis shows that the plots are quite similar. 

I do not know much about the algorithms for a KDE, but @ahartikainen might have some opinions about whether we want to pad out the left and right edges of the data with 0's.

![image](https://user-images.githubusercontent.com/2295568/52276857-43395080-2921-11e9-86b9-d9fea4d47572.png)

**Comment by aloctavodia** [comment]
@absolutelyNoWarranty thanks for taking the time to report this issue.

My opinion on this issue is that ArviZ is doing the a good job here, Pandas/Scipy's KDE do not respect the boundaries. In this example the result is over-smoothing the tails. Is not right to plot the density at the tail if you do not have data at the tails, at least not for a tool like ArviZ, this will show information about the posterior that is not there, if you want nicer tails, then you need more samples. Of course, for other tools people might argue that as a KDE is a quick way to perform inference about the density of the data the result by Pandas is a better one given that it looks closer to the the _true_ distribution. But for ArviZ this will be misleading.

**Comment by aloctavodia** [comment]
ohh, you are right about the normalization. We used to compute the normalization constant and then I change that! Probably we should revert that change.

**Comment by absolutelyNoWarranty** [comment]
@aloctavodia For reference, I actually found this bug while reading your book. Specifically it breaks the plots in chapter six.

Chapter six figures: 
<img src=https://raw.githubusercontent.com/aloctavodia/BAP/master/code/Chp6/B11197_06_02.png width="45%" height="45%"> <img src=https://raw.githubusercontent.com/aloctavodia/BAP/master/code/Chp6/B11197_06_08.png width="70%" height="70%">

But with the scaling issue for me they look like:

<img src=https://user-images.githubusercontent.com/1489338/52321394-7ce88500-2a0f-11e9-97e3-33237af83011.png width="45%" height="45%">

<img src=https://user-images.githubusercontent.com/1489338/52321699-faf95b80-2a10-11e9-8b36-acbce2237ac0.png width="70%" height="70%">

**Comment by aloctavodia** [comment]
I hope you are enjoying it. We will fix this issue soon. BTW, the code in the book was done and tested using ArviZ 0.3.1
