### ISSUE TITLE
Rename from_pymc3(prior) arg to prior_predictive and add prior arg

### ISSUE THREAD

**Issue by canyon289** [arviz-devs/arviz#597]
## Tell us about it
Is it unclear whether prior means prior_predictive, or prior samples from reading docs.
https://arviz-devs.github.io/arviz/generated/arviz.from_pymc3.html#arviz.from_pymc3

From tests though it looks like this argument should be prior predictive
https://github.com/arviz-devs/arviz/blob/master/arviz/tests/test_data.py#L640

Proposal is to rename `prior` to `prior_predictive` and include a method for prior samples to be stored in `az.InferenceData`

## Thoughts on implementation
Rename argument to be specific like pystans method
https://arviz-devs.github.io/arviz/generated/arviz.from_pystan.html#arviz.from_pystan

@ColCarroll @aloctavodia 
Let me know what you think and I can go ahead and do this

**Comment by canyon289** [comment]
Hmm, Now I'm realizing prior in pymc3 is both prior samples, and posterior predictive put together. Maybe instead of rename I can just add documentation?

**Comment by ColCarroll** [comment]
> prior in pymc3 is both prior samples, and posterior predictive put together

Yeah, we talked about this in the naming, too. It was just easier to put them all together, instead of requiring prior draws, and then prior predictive draws.

**Comment by canyon289** [comment]
Ok will add documentation instead. Thanks!

**Comment by canyon289** [comment]
Reopening to keep in mind that docs need to be written to explain behavior

**Comment by rpgoldman** [comment]
Related to the above, it's not obvious from the documentation how one goes about plotting samples from the prior distribution. There aren't examples in the cookbook or get started guide (or I missed them), and the API summary table is so terse that the reader can't tell which of the plotting functions take `group` as an argument.  It looks like I should be able to do this with `plot_density`, but as I said, it wasn't obvious from the docs.
Two good enhancements would be:
1. Give examples of plotting trace, prior predictive, and posterior predictive distributions in the cookbook.
2. It would be better to give *all* of the arguments to the plot functions in the main API page.  I get it that there are a lot of them, and it would make that page more cumbersome, but it seems like the only way to make it clear which of the plotting functions are applicable to, e.g., the priors, and which are only applicable to the posterior samples.

**Comment by ahartikainen** [comment]
I think many of our plots are missing `group` kw.

**Comment by OriolAbril** [comment]
#909 implemented a partial fix that divides prior and prior predictive into their respective groups whenever possible.

**Comment by rpgoldman** [comment]
What's the prior in the context of PyMC3?  I think the prior is implicit in the model, right?

**Comment by aflaxman** [comment]
I haven't followed this PyMC development of this method carefully, but this PR could potentially help you sort it out: https://github.com/pymc-devs/pymc3/pull/2983

**Comment by rpgoldman** [comment]
I read over that, but I still don't see a clear explanation of the prior/prior predictive distinction (indeed, I'm tempted to call it a "putative distinction").

In that discussion @ColCarroll says he has been having trouble formulating the distinction clearly.   Allen Downey says that perhaps all we need is prior predictive and not both pp and prior.  AFAICT there is no "prior sample" function in PyMC3.  So I still don't see a clear formulation of the distinction.

**Comment by OriolAbril** [comment]
The prior predictive is to the prior what the posterior predictive is to the posterior. Even though both quantities are obtained with pymc's `sample_prior_predictive` they are conceptually different. Let's take as examples the prototype plots from #749, the first one uses prior and posterior samples and the second uses prior predictive, posterior predictive and also observed values.

When the trace is present, there is no problem in the prior/prior predictive separation, the variables in the trace (used to get the variables in the posterior group) are used to get the variables in the prior group. However, as `from_pymc3` can work without a trace, having as input only the "prior" dict (the result of `pm.sample_prior_predictive`) there are some cases where there is no information available to divide the variables.

**Comment by rpgoldman** [comment]
> The prior predictive is to the prior what the posterior predictive is to the posterior. Even though both quantities are obtained with pymc's `sample_prior_predictive` they are conceptually different. Let's take as examples the prototype plots from #749, the first one uses prior and posterior samples and the second uses prior predictive, posterior predictive and also observed values.

I'm afraid I  don't understand your analogy (sorry!)

For the posterior/posterior predictive comparison we have in PyMC3 `sample`/`sample_posterior_predictive`.  For prior/prior predictive we have ????/`sample_prior_predictive`.  I don't see what fills the role of ???? here.  The example in #749 does not exhibit the four different possibilities in your comment, so it doesn't really help me.  In particular, I don't see a distinction between prior and prior predictive.
> 
> When the trace is present, there is no problem in the prior/prior predictive separation, the variables in the trace (used to get the variables in the posterior group) are used to get the variables in the prior group. However, as `from_pymc3` can work without a trace, having as input only the "prior" dict (the result of `pm.sample_prior_predictive`) there are some cases where there is no information available to divide the variables.

For this reason, my proposed solution #983 adds a `model` argument to `from_pymc3()`.  The model provides the necessary information to divide the variables and also more appealing than taking the undocumented backpointer out of a `MultiTrace`.  I don't see any reason we should avoid using the information in the PyMC3 `Model` object.

**Comment by OriolAbril** [comment]
Don't worry, I'll try to explain myself better. And provide a kind of conceptual analogy, one example and a link to their proper definitions. 

I think I should start by noting that when I make analogies between diferent quantities I talk at a conceptual level, I know that in PyMC some analogies do not translate to the implementation, hence the confusion. [This proposal](https://github.com/pymc-devs/pymc3/pull/2983#issuecomment-394039293) might have avoided the issue. Saying that the prior predictive is the the prior what the posterior predictive is to the posterior means that the prior and the posterior give information about the same variables, and the predictive ones also give information about a common set of variables, which are different to the previous ones.

 On a more applied note, this means that you can compare the prior and the posterior distributions to see how do observations affect the probability distribution, but you cannot compare them to neither of prior predictive, posterior prerictive nor observed data. The same happens the other way around, the prior predictive cannot be compared to the posterior. The plot in #749 shows this, one figure has prior and posterior and the second figure has prior predictive, posterior predictive and observed data.

Also, for anybody who prefers maths, this [cross validated question](https://stats.stackexchange.com/questions/394648/differences-between-prior-distribution-and-prior-predictive-distribution) includes the definitions.

**Comment by rpgoldman** [comment]
OK, that helps a lot.

I think that if I was to translate the distinction into PyMC3 terms, we could say:

1. The `prior` is samples over all of the variables in the graph.  This would be implemented by using PyMC3's `sample_prior_predictive` but asking it to return values for *all* the variables (i.e., the full list of variables would be in the `var_names` argument).

2. In PyMC3 terms, the `prior_predictive` would refer to `sample_prior_predictive` called with the default arguments -- i.e., only the observed random variables would be sampled.

If I understand this right, this is still an imperfect parallel, because in PyMC3 terms the prior predictive distribution is a projection of the prior distribution.

The posterior and posterior predictive distributions are not quite parallel, because of the special role of the observed random variables.  In this sense, where the prior predictive is a projection of the prior onto the observed RVs, in PyMC3 the *full* posterior distribution would be gotten by first sampling (to get values for the latent variables) and then invoking `sample_posterior_predictive` to get the values of the observed RVs.  If one thinks of the "true posterior" in this way, then the parallel is restored: the posterior predictive is a projection of the "true posterior", the way the prior predictive is a projection of the prior.

Note that I'm a little handicapped here because I'm not familiar with other frameworks like Stan, so I don't have the wider perspective you have.

**Comment by OriolAbril** [comment]
I currently cannot comment on the internals of the sampling process in `sample_prior_predictive`, only about the variables it samples. I kind of remember stumbling into an issue using ArviZ with the `sample_prior_predictive` including variables it was not supposed to and trying to fix it (I am quite sure I actually sent a PR about this) and the default was `sample_prior_predictive` sampling both prior and prior predictive values. I fear I don't follow the translation to PyMC3 terms, sorry. 

I think this is relevant because in addition to the conceptual clarification that might help the schema specification, this will probably reveal some issues in ArviZ handling of prior/prior predictive in `from_pymc3` and in the default variables for pymc3 `sample_prior_predictive`.

**Comment by rpgoldman** [comment]
The thing my PR fixes is that you can't determine what is constant and what is not based on the trace that `sample_prior_predictive` returns (or really, the return of *any* PyMC3 sampling function).  The reason is that PyMC3 allows the user to control what variables do and do not appear in the traces that the sampler returns.
That is why, as far as I can tell, we *must* give `from_pymc3` the PyMC3 model as an argument: without access to the model, the translator simply doesn't have enough information to allocate variables to groups.
Note also that using the backdoor from the posterior trace doesn't generally work, either, since if you are doing predictions out of sample, you *must* create a new PyMC3 model and use the *old* trace with the *new* model -- meaning that the model cached in the posterior trace is the wrong model.

**Comment by OriolAbril** [comment]
Maybe there should also be some check in PyMC part? There should be nothing constant in the return values of `sample_prior_predictive`, all variables should have dims `sample, *shape` and have a different value per sample right? 

Kind of like the posterior with `chain, draw, *shape`. Would it be possible to have the same value for every chain and draw?

**Comment by rpgoldman** [comment]
What I have done instead (with the help of Brandon) is to check any nodes that are deterministic functions to see if they have only constants in their input subgraph.  IF they do, then they go into the predictions constant data, else they go into the predictions.

The deterministic nodes are the only named entities that are difficult to allocate between constant and varying, and Brandon's analysis of the theano model graph disambiguates them.

**Comment by OriolAbril** [comment]
I think we can close this now

**Comment by rpgoldman** [comment]
I agree: we can look at the model and the trace(s) and figure out how to allocate the information between the two groups ourselves, instead of asking the users to.
