### ISSUE TITLE
Is there some way to plot individual chains (from PyMC3 data)?

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#654]
## Short Description

I have a data set with four chains where one of them is going badly wrong:

<img width="408" alt="image" src="https://user-images.githubusercontent.com/3274/56816333-f327a700-6808-11e9-9810-682587256fb7.png">

It would be nice if I could plot the individual chains separately (i.e., in subplots), and if the plots would display the index of the chain in the plot legend (i.e., add a key to the plot which would show the mapping between chain index and color).

Thanks!

## Library versions:
Arviz 0.3.3 and PyMC3 3.6

**Comment by ColCarroll** [comment]
Gosh, the code is _very_ close to letting you do this. I should be able to make a quick p.r. in the next few days to add a `label={chain_idx}` to each line, so that
```python
import arviz as az

schools = az.load_arviz_data('centered_eight')

axes = az.plot_trace(schools, 'mu')
axes[0, 0].legend();
```

will put a legend in the top left subplot (note there's no labels yet, so this gives an empty legend right now). 

This also _almost_ works, but throws an `IndexError` when it tries to get the divergences from chains 3 and 4:

```python
import arviz as az

schools = az.load_arviz_data('centered_eight')

axes = az.plot_trace(schools, 'mu', coords={"chain": [1, 2]});
```
