### ISSUE TITLE
plot pointwise WAIC/LOO

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz#660]
ArviZ is missing function to compare models in terms of pointwise ELPD. See [figure 10](https://arxiv.org/abs/1709.01449). 

Such a function could work for 2 models (like figure 10) or for more than 2 and return a grid of non-redundant subplots, like `plot_pair`.

**Comment by OriolAbril** [comment]
I will start working on this. Here is the main idea to make sure we are on the same page. 

    def plot_compare_pointwise(idata_dict, ic="waic", color=None, ...):
        """Graphical comparison of multiple models in terms of pointwise ELPD.

        idata_dict : mapping (str -> InferenceData)
            Dictionary mapping the name of each model to compare to its corresponding InfereceData
        ic : str, optional
            Information Criterion (WAIC or LOO) used to compare models. Default WAIC.
        color : str or array_like, optional
            Colors of the scatter plot, if color is a str all dots will have the same color, if it is the size of the observations, each dot will have the specified color, otherwise, it will be interpreted as a list of the dims to be used for the color code.
        """
        # behaviour similar to plot_pair with pointwise ELPD plots

I was also thinking that in addition to the color code, it may be useful to have a coords argument, in order to plot only a subset. It could be interesting in the radon case for instance. I will give some more thinking to the API and start a PR soon.
