### ISSUE TITLE
CmdStanPy tests

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#673]
Add tests for CmdStanPy. See if we can read cmdstan output csv to PosterierSample which then can be tested.

**Comment by mitzimorris** [comment]
CmdStanPy is very beta, alas.  PR https://github.com/stan-dev/cmdstanpy/pull/43 was a refactor which eliminated object `PosteriorSample` and made some of its member functions into first-class functions.  Instead of a `PosteriorSample` object, function `sample` returns a `RunSet` object.    Need to update `from_cmdstanpy` accordingly.

**Comment by ahartikainen** [comment]
Yes, I can make the changes.

Did cmdstanpy have functionality to read csv to Runset?

**Comment by mitzimorris** [comment]
Yes, the RunSet object parses the csv and populates the following properties:

+ `draws` - number of draws per chain  (sampling iterations)
+ `columns` - total number of columns in the csv output - includes sampler state as well as model parameters, transformed parameter and generated quantities variables
+ `column_names` - csv column headers
+ `sample` - a 3-D numpy ndarray which contains all draws across all chain arranged as (draws, chains, columns) stored column major so that the values for each parameter are stored contiguously in memory, likewise all draws from a chain are contiguous.
+ `stepsize` - stepsize used by sampler for each chain.
+ `metric` - metric used by sampler for each chain.

If you look at the dimension of the metric, you'll get the number of parameters in the model - is that useful?  the csv columns are arranged:  sampler state, parameters, transformed parameters, generated quantities.  sampler state output names end in `_`.

The `sample`, `stepsize`, and `metric` properties are populated lazily - the first any of them are accessed, the RunSet class method `assemble_sample` is called.

hope this helps.

**Comment by mitzimorris** [comment]
Reading through `arviz/data/converters.py` -
I think that you only need to change `PosteriorSample` to `RunSet` in the the following 2 lines:
```
70:        obj.__class__.__name__ in {"StanFit4Model", "PosteriorSample"}
77:        if obj.__class__.__name__ == "PosteriorSample":
```

**Comment by mitzimorris** [comment]
tried this out locally and then ran the CmdStanPy tutorial notebook, adding the following - it just works!
<img width="1248" alt="arviz_from_cmdstanpy" src="https://user-images.githubusercontent.com/5466612/59967878-dbb22500-94fe-11e9-9c0d-e88fa817d297.png">

**Comment by ahartikainen** [comment]
Yes, I tried it too, we only need to change `PosteriorSample` to `RunSet`.
