### ISSUE TITLE
Older pymc3 compatibility

### ISSUE THREAD

**Issue by ahartikainen** [arviz-devs/arviz#732]
Is current master (git) compatible with latest released pymc3? Due to posterior predictive sampling and `keepsize` parameter.

Can we add manually fix this, e.g. transforming posterior predictive shape for older pymc3?

**Comment by OriolAbril** [comment]
The handling of posterior predictive samples in `from_pymc` considers 3 cases:
* ideal "old" pymc: if the first dimension is equal to `nchains*ndraws` it reshapes the array, to fit ArviZ way.
* "new" pymc: if the first dimensions are `chain, draw` it converts to dataset right away.
* non ideal case: otherwise, it sends a warning and all posterior predictive samples are stored as `chain=0`

As the CI environment is built from pymc master branch, ArviZ already has test for `keepsize` parameter (added in #702).

What will fail is using the `size` parameter, to get more than one pp sample per posterior sample.

**Comment by ahartikainen** [comment]
Ok, this is great news.

My tests were failing locally.

Closing this one.

**Comment by ColCarroll** [comment]
For what it is worth, I updated the posterior predictive sampling in PyMC3. The "new" behavior by default gives you posterior predictive samples in the exact order as your posterior samples, so you can do joint/marginal plots.

**Comment by OriolAbril** [comment]
Could it be you had an old pymc version? If I remember correctly I added no skipif so it probably tried to use keepsize and raised an error due to nonexisting parameter.

@ColCarroll Yes! I saw that, otherwise it would not have made any sense to assign posterior predictive samples to a given chain and draw. Made my life much easier, thanks!

**Comment by ahartikainen** [comment]
My pymc3 is from pip
