### ISSUE TITLE
plot_ppc - ax argument not recognised

### ISSUE THREAD

**Issue by evitaka** [arviz-devs/arviz#789]
**Describe the bug**
When I use the plot_ppc() method and I want to set the axes object as an argument of the method, I get an error that this argument is not recognised. However, the [API reference](https://arviz-devs.github.io/arviz/generated/arviz.plot_ppc.html#arviz.plot_ppc) for this method clearly states that this argument is supposed to be there for this plot method. 

**To Reproduce**
`import arviz as az`
`import matplotlib.pyplot as plt`
`data=az.from_netcdf('./PyMC3_fullyPooledModel.nc')`
`fig, ax1 = plt.subplots()`
`az.plot_pcc(data, ax=ax1)`

**Expected behavior**
I was expecting to be able to set the axes object for plotting the ppcs.

**Additional context**
Arviz 0.4.1
Python 3.7.3
Windows 10

**Comment by OriolAbril** [comment]
Hi, thanks for the issue!

The `ax` argument in `plot_ppc` was added recently (in #773) and is not present yet in any release. It is in the docs because the docs refer to the development version. You can install the development version with `pip install git+git://github.com/arviz-devs/arviz.git` which should solve the problem.

If you have any other issue or this does not fix the problem, please comment again

**Comment by aloctavodia** [comment]
I will close this issue, but @evitaka feel free to keep posting
