### ISSUE TITLE
Can't change predictors in posterior_predictive trace

### ISSUE THREAD

**Issue by rpgoldman** [arviz-devs/arviz#829]
**Describe the bug**
A common thing to want to do is to train a model, and then use posterior predictive sampling to predict responses to new predictor values.
As far as I can tell, this cannot be done with the present version of Arviz.

Why is this?  Because when one builds an `InferenceData` object with a posterior trace and a posterior predictive trace that has a different set of predictors, the dimensions of the variables in the posterior predictive trace, in general, will not agree with the dimensions of the same variables in the posterior trace, because the predictor values are different.

One could imagine building an `InferenceData` object with *only* the posterior predictive trace, and no posterior trace.  This seems not to work, either.  The reason is that if one looks at the `posterior_predictive_to_xarray` method in `io_pymc3.py`, one sees that the interpretation of the posterior predictive trace argument is based on the `nchains` and `draws` properties of the translator, which are harvested from the posterior trace.

I will try to scratch together a reproducible test case, but the above should be enough to get started -- the issues are clear from looking at the source code.

## Big design issue

I believe that the issues in dealing with models that contain external values/predictors display at least two fundamental problems with `InferenceData`:

1. If we are to make predictions outside the training set, we cannot assume that the coordinates for the posterior trace group will be the same as the coordinates for the prior or posterior predictive groups, and equivalently, the shapes of the random variables may be different across the different groups.

2. An alternative would be to make it possible to create `InferenceData` objects that **only** contain prior predictive or posterior predictive traces.  But to do this,  `from_pymc3()` needs to be overhauled, because it makes many assumptions about the availability of the posterior trace, and relationships between it and the predictive traces.

**Comment by ahartikainen** [comment]
Can you give an example?

What I think, is that there should be 1to1 relation between `posterior` draws and `posterior_predictive` "draws".

And similar thing applies to `prior` and `prior_predictive`

Currently we also have "1to1" relation with `posterior_predictive` and `observed_data`.

What you want is to also have other "unseen" `posterior_predictive` values --> yes I think we are missing this, and we should support it. Then we still should have 1to1 relation with `posterior` and we should have some convenient way to separate values related to `observed_data` and "missing_data".

**Comment by rpgoldman** [comment]
Sure, here's my exact example:

I have data from synthetic bio experiments where different strains of cells are grown under different growth conditions.  The output measure is fluorescence, measured by flow cytometry.

So the predictors/independent variables are strain, growth conditions (temperature, growth medium, and population density).

I train on a large set of samples/rows, so I have a set of output variables, whose dimension is the number of rows (this is done because the model is localized, per Blei).

So I put in a dataframe of samples, do MCMC, and collect a posterior trace.

Then I put in a *new* dataframe of queries (hypothetical combinations of strain and growth conditions) and do posterior predictive sampling.  The resulting trace I do not know how to use with arviz, because interpreting it requires the information in the model (which is harvested by arviz by looking through the posterior trace into the model), and the dimensions of the posterior predictive samples are not the same as the dimensions of the posterior samples.

**Comment by rpgoldman** [comment]
Here's a graphviz diagram of the model.
[model.dot.txt](https://github.com/arviz-devs/arviz/files/3632976/model.dot.txt)

**Comment by OriolAbril** [comment]
I took the liberty of generating a somehow simpler example to help with my views on the topic. To begin with, I do like the 1to1 relation @ahartikainen was talking about and I would like to keep it and enforce it, that it is difficult (or not even possible) to store predictions on different predictors than the ones used when calculating the posterior is indeed good. What is not good is ArviZ not having (yet) some way of working with predictions obtained using the inference results. 

The example tries to have some resemblance to an engineering problem, but it is completely synthetic and invented. We have a material whose resistance to stress is optimal around 20degC and it decreases as we depart from this peak value. We use some measures and a given model to estimate some parameters of the material in order to estimate the resistance at different temperatures where there are no measurements (either interpolating or extrapolating). So, without further ado, here is the code:

```python
import numpy as np
import pymc3 as pm
import arviz as az

import matplotlib.pyplot as plt

np.random.seed(10)

n = 10
temperature = np.linspace(-15, 50, n)  # T in celsius
# any dependence with a peak resistance to make it interesting
resistance_obs = (-.1 * temperature**2 + 8 * temperature + 150) / (temperature + 33) + np.random.normal(0, .1, size=n)

# fit model
with pm.Model() as model:
    T = pm.Data("T", temperature)
    n1 = pm.Normal("n1", sigma=10)
    n0 = pm.Normal("n0", sigma=200)
    n2 = pm.HalfNormal("n2", sigma=2)
    d0 = pm.HalfNormal("d0", sigma=30)
    sigma = pm.HalfNormal("sigma", sigma=1)
    
    resistance = pm.Normal(
        "resistance", 
        (- n2* T**2 + n1 * T + n0) / (T + d0), 
        sigma,
        observed=resistance_obs
    )
    
    trace = pm.sample(draws=3000, chains=4, tune=3000, random_seed=[1, 8, 5, 9]);
    posterior_predictive = pm.sample_posterior_predictive(trace)

idata = az.from_pymc3(trace, posterior_predictive=posterior_predictive)
```

The first step would be to fit the model on the data we have available and in addition, check (at least a little) the convergence of the MCMC and the model itself (i.e. using posterior predictive checks). We can easily do this in ArviZ:

```python
# check convergence
az.summary(idata)

# check model
mean = idata.posterior_predictive.resistance.mean(dim=("chain", "draw"))
std = idata.posterior_predictive.resistance.std(dim=("chain", "draw"))
idata.posterior_predictive["scaled_res"] = (idata.posterior_predictive.resistance - mean) / std
idata.observed_data["scaled_res"] = (idata.observed_data.resistance - mean) / std
az.plot_ppc(idata, var_names="scaled_res", num_pp_samples=200)

# more model checking
az.plot_loo_pit(idata, y="resistance");
```
These functions rely on the 1to1 relation between the posterior, posterior_predictive and observed_data, modifying their contents breaking this relation would create `InferenceData` objects
that cannot be used as inputs for these functions (and assuming that shapes did match, there would be no way of telling afterwards). Hence, here is where I link #220 as this is a clear candidate for a new group. I also think it would be a great idea to sit and think about the inference data schema, what does well, what is it missing, document its groups and what should be their content... 

Below is one possibility on treating this new predictions: storing them in a new group. It is not much more than an idea, as I am using non-public methods, the new predictors are not stored anywhere... we can talk about this later. 

```python
# use model to predict (by using the posterior samples)
with model:
    pm.set_data({"T": np.linspace(10, 30, 40)})
    predictions = pm.sample_posterior_predictive(trace, keep_size=True)

# merge predictions into InferenceData
idata_predictions = az.InferenceData(predictions=az.data.dict_to_dataset(predictions))
az.concat(idata, idata_predictions, inplace=True)
idata  # check how a new group called predictions is present

# work with predictions
az.plot_posterior(idata, coords={"resistance_dim_0": slice(18, 26)}, group="predictions", ref_val=4.9);

# in whatever way preferred
ax = az.plot_hpd(np.linspace(10, 30, 40), idata.predictions.resistance)
ax.plot(np.linspace(10, 30, 40), idata.predictions.resistance.mean(dim=("chain", "draw")), "C1");
```

The whole example should be executable just by copy pasting in order to ease playing with this example and the idea. I hope I was able to explain myself clearly, let me know what you think.

**Comment by OriolAbril** [comment]
#916 could be a solution to this issue.
