### ISSUE TITLE
plot_trace with `combined=True` to have alternating colors and labels

### ISSUE THREAD

**Issue by julian-pani** [arviz-devs/arviz#837]
## Tell us about it

I'm very new at this, so not sure how much this problem is relevant for other users.
When using `plot_trace` with `combined=True`:
```python
import matplotlib as plt
import arviz as az
data = az.load_arviz_data('non_centered_eight')
ax = az.plot_trace(data, var_names=('theta_t', 'theta'), combined=True, compact=True, figsize = (20, 8))
```
the lines come up in the same color and without labels, so it's hard to differenciate between them
![Screenshot from 2019-09-30 17-06-18](https://user-images.githubusercontent.com/8047789/65886247-aa21e300-e3a4-11e9-9e59-4194e5fcb6dd.png)

It would be great to have colors by default in the lines. And maybe an option to show labels
Something like:
![Screenshot from 2019-09-30 17-05-55](https://user-images.githubusercontent.com/8047789/65886261-af7f2d80-e3a4-11e9-908b-7a26a33a9d51.png)

## Thoughts on implementation
Alternating colors - I don't see any reason not to have them.
For the labels - I understand that there could be thousands of lines, so maybe have a limit, to show something like the first 5 labels, or maybe add an argument to the method with `num_labels` (and then show "..." to indicate there are more not being shown)

I've been looking at https://arviz-devs.github.io/arviz/_modules/arviz/plots/traceplot.html for a while but it's way above my league. I just don't understand what's going on.

Thanks for reading!

**Comment by canyon289** [comment]
@julian-pani Apologies on missing this issue for the last couple months. 

The traceplot lines should show up in different colors now. I checked the latest example to verify. Are you still having this issue?

https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_trace.html

**Comment by OriolAbril** [comment]
I think it is still an issue, because `plot_trace` accepts both `combined` and `compact` argument. Thus, there are 4 cases to take into account:
1. `combined = compact = False` (default case). Multidimensional variables are plotted on different subplots, and chains are not combined, thus, each kde subplot has `nchains` lines. This is the case of the example, where each line has a different color. Moreover, using `legend=True` will automatically generate a legend with the chain color code.
1. `combined = True; compact = False`. Multidimensional variables are plotted on different subplots, and chains are combined. Thus, each kde subplot has 1 line. I don't think legend would currently work in this case, but the title already gives all the information, it is not a priority to get a legend working here.
1. `combined=True; compact=True`. Multidimensional variables have all components plotted in the same subplot (this is @julian-pani's case). Thus, each subplot has as many lines as the dimension of the variable. Legend and coloring do not work because they currently only code chain information.
1. `combined=False; compact=True`. Multidimensional variables have all componensts plotted in the same subplot, and chains are not combined. Each subplot has `nchains*shape` lines. The color and legend should correctly represent the chain information, but all the information on the variable coordinate is lost (much like in the previous case). 

The solution would be to have:
1. Coloring and legend based only on chain. Already implemented.
1. Nothing to implement I think.
1. Coloring and legend based only on variable coordinate. **TODO**
1. Coloring based on chain and linestyle? based on coordinate (or viceversa, depending on new arg/rcparam/which is larger). I think the ideal case would be having 2 legends, one with the chain info and the other with the coordinate info. **TODO**

**Comment by AbhishekKumarSingh** [comment]
use compact=False and it should work. By default compact=True in newer version.

ax = az.plot_trace(data, var_names=('theta_t', 'theta'), compact=False, figsize = (20, 8))
