### ISSUE TITLE
ArviZ incompatible with pyro 0.5

### ISSUE THREAD

**Issue by OriolAbril** [arviz-devs/arviz#845]
**Describe the bug**
The most recent CI builds fail when using pyro 0.5. Here is what I think is the relevant part of the code to run the model for testing:

```python
...
nuts_kernel = NUTS(_pyro_conditioned_model, adapt_step_size=True)
posterior = MCMC(  # pylint:disable=not-callable
    nuts_kernel, num_samples=draws, warmup_steps=500
).run(_pyro_centered_model, sigma, y)

# This block lets the posterior be pickled
for trace in posterior.exec_traces:
    for node in trace.nodes.values():
        node.pop("fn", None)
posterior.kernel = None
...
```

I have seen that in the latest release `.run` does not return anything, however, moving it to the next line in the form of `posterior.run()` does not solve the issue as `exec_traces` is not an attribute of MCMC objects. Moreover, `exec_traces` is also used in `from_pyro`. Any ideas? i.e. @fehiepsi ?

**Comment by fehiepsi** [comment]
@OriolAbril The new version of MCMC does not hold `exec_traces` anymore. Instead, all posterior samples can be obtained with [get_samples](http://docs.pyro.ai/en/stable/mcmc.html#pyro.infer.mcmc.api.MCMC.get_samples) method. So the `posterior_to_xarray` method will be simpler than before. But we will not be able to access `observed_data` using the latest Pyro version (because no trace is stored). We will make sure that it is doable in Pyro 1.0 (which is scheduled next month). cc @neerajprad

Do you want me to make a PR to update `from_pyro` for the latest version? If you are willing to do, I am happy to review it. :)

**Comment by OriolAbril** [comment]
I don't have much time right now, so feel free to make a PR if you do, I will try to review it as soon as possible. 

Moreover, given that `io_pyro` has to be modified, it is probably time to set a minimum pyro version and make ArviZ only support recent ones? It may be too much work and not very useful to try to support everything given the differences in retrieving the data.

Also it we should update the CI that runs with an old version of pyro because it is a really old version.

**Comment by fehiepsi** [comment]
Yeah, I'll make a PR soon. :)

**Comment by fehiepsi** [comment]
I think we can close this issue.
