### ISSUE TITLE
ArviZ docs should be built off latest release, not master

### ISSUE THREAD

**Issue by eigenfoo** [arviz-devs/arviz#896]
**Describe the bug**
As in the title.

**To Reproduce**
For example, currently [the `plot_forest` doc page](https://arviz-devs.github.io/arviz/generated/arviz.plot_forest.html#arviz.plot_forest) lists the `plot_forest` function to take the `coords` argument, and the little `0.5.1` in the navigation bar immediately made me think it was a released feature in `0.5.1`. However, this was only merged in https://github.com/arviz-devs/arviz/pull/835, which has not yet been released.

**Expected behavior**
Ideally there would be a set of built docs for every version, but I realize that ArviZ is still in beta and that that would be a lot of work. However, I think it's reasonable to expect that the served docs document only the latest release of ArviZ.

**Additional context**
I would be happy to submit a patch for this, but I'm not really sure about the docs pipeline. I assume [this line in the `deploy_docs.sh` file](https://github.com/arviz-devs/arviz/blob/master/scripts/deploy_docs.sh#L5) is relevant, but I suspect it's not a one-line change...

**Comment by canyon289** [comment]
My suggestion for this is that in the CI build there is an env var that has the branch name. If the branch name contains release then deploy docs.

**Comment by aloctavodia** [comment]
On PyMC3 we have this, https://github.com/pymc-devs/pymc3/blob/master/build_and_deploy_docs.sh, that needs to be run manually I guess

**Comment by sethaxen** [comment]
Why not deploy both release and dev documentation builds? We're doing this in [ArviZ.jl](https://github.com/arviz-devs/ArviZ.jl).

But I also am a big fan of continuous delivery, making frequent patch releases so that if one is installing the latest release using pip, it's unlikely that there's any discrepancy between that version and even the dev docs.

**Comment by oscarbranson** [comment]
Following on from #1196:

The docs currently have '0.7.0' written at the top of the page and in the page title, implying that they relate to the latest release.

Until this is resolved, would it be possible to append '-dev' to the docs label to make it clear that it relates to the dev branch and not the latest release?

**Comment by OriolAbril** [comment]
For the time being, `dev` is used as version indicator in online docs (see #1204). Docs generated locally should still use the correct version number.

Docs generated from a tag instead of master branch CI will also show the correct tag in hopes that could help in getting both releases and dev documentation in the website

**Comment by OriolAbril** [comment]
I think https://github.com/c-w/ghp-import/issues/74 could be used to solve that by storing the builds from `master` branch in `dev` folder and then modify azure to build docs from tags too and store them in the version (i.e. `0.9.0`) folder. There may be a couple of extra details to take care of like a new `index.html` automatically pointing to `stable` folder, having stable as a symlink of the latest release (so default page shows stable instead of dev docs) and/or maybe a json with version info

**Comment by OriolAbril** [comment]
This is kind of fixed already now that we have readthedocs set up: https://arviz.readthedocs.io/en/latest/ has the version dropdown to choose which one you want.

Now we only need to link to it, preferably via a custom url.

**Comment by OriolAbril** [comment]
Closing as it is superseeded by #2012
